name: trading-journal
region: nyc

databases:
  - name: db
    engine: PG
    production: true
    version: "15"

services:
  - name: backend
    github:
      repo: theluckymak/trading-journal
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
      - path: /docs
      - path: /redoc
      - path: /health
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ${SECRET_KEY}
      - key: ALGORITHM
        scope: RUN_TIME
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        scope: RUN_TIME
        value: "30"
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"
      - key: REDIS_URL
        scope: RUN_TIME
        value: "redis://localhost:6379/0"
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  - name: frontend
    github:
      repo: theluckymak/trading-journal
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}
      - key: NEXT_PUBLIC_API_URL_SERVER
        scope: RUN_AND_BUILD_TIME
        value: http://backend:8000
    build_command: npm install && npm run build
    run_command: npm start
